### ISSUE TITLE
Soundness issue: AtomicBox Sync+Send impls are too broad

### ISSUE THREAD

**Issue by geeklint** [jorendorff/atomicbox#5]
AtomicBox has blanket Sync+Send impls, which allows non-Send items to be sent to other threads.

I believe it's safe for `AtomicBox<T>` to be Sync even if `T` is only Send, (same as `Mutex<T>`) but it's definitely not safe for `AtomicBox<T>` to be Sync+Send if `T` is neither.

Sample: Atomic Box allows Rc to be sent to other thread (tested with atomicbox = "0.3.0")
```rust
use std::rc::Rc;
use atomicbox::AtomicBox;

fn main() {
    let rc_main = Rc::new("Hello, world!");
    let rc_other = Rc::clone(&rc_main);

    let abox = AtomicBox::new(Box::new(rc_other));
    let handle = std::thread::spawn(move || {
        let value = *abox.into_inner();
        println!("Other thread: {:?}", value);
    });
    handle.join().unwrap();
    println!("Main Thread: {:?}", rc_main);
}
```

**Comment by jorendorff** [comment]
Ugh. Thanks for the report.
