### ISSUE TITLE
Add const fn to generate null AtomicOptionBox?

### ISSUE THREAD

**Issue by nyanpasu64** [jorendorff/atomicbox#6]
I was thinking of using AtomicOptionBox in a static variable, which can only be initialized using a const fn. Is the following worth adding to the library?

```rust
impl<T> AtomicOptionBox<T> {
    ...
    pub const fn new_none() -> AtomicOptionBox<T> {
        AtomicOptionBox {
            ptr: AtomicPtr::new(null_mut()),
        }
    }
```

**Comment by jorendorff** [comment]
Good call. This is in version 0.4.0, thanks to #3 by @kennytm.
